#source("generate_documentation.R")

unlink("src/*.cpp")
unlink("src/*.c")
unlink("src/*.h")
unlink("src/*.o")
unlink("src/*.so")
unlink("src/*.dll")

flstFV <- list.files("src/fvlib/")
flstGA <- list.files("src/GAlib/")
flstDA <- list.files("src/DAlib/")
flstITER <- list.files("src/ITERlib/")
frm <- paste("src/fvlib/",flstFV,sep="")
frm <- c(frm,paste("src/GAlib/",flstGA,sep=""))
frm <- c(frm,paste("src/DAlib/",flstDA,sep=""))
frm <- c(frm,paste("src/ITERlib/",flstITER,sep=""))
#print(frm)
file.copy(from=frm,to="src", overwrite = TRUE)
