roxy_files <- c(
		"add.phdata.R",
		#"annotation",
		"arrange_probabel_phe.R",
		"blurGenotype.R",
		"checkPackageVersionOnCRAN.R",
		"del.phdata.R",
		"egscore.R",
		"estlambda.R",
		"export.plink.R",
		"extract.annotation.impute.R",
		"extract.annotation.mach.R",
		"findRelatives.R",
		"GC.R",
		"GC_ovdom.R",
		"GenABEL.R",
		"generateOffspring.R",
		"getLogLikelihoodGivenRelation.R",
		"grammar.R",
		"hom.R",
		"ibs.R",
		"impute2databel.R",
		"impute2mach.R",
		#"LiLogCC.R",
		#"LiLog.R",
		"mach2databel.R",
		"makeTransitionMatrix.R",
		#"phdata.R",
		"PGC.R",
		"polygenic.R",
		"polygenic_hglm.R",
		"qtscore.R",
		"recodeChromosome.R",
		"reconstructNPs.R",
		"sortmap.internal.R"
		#,
		#"summary.scan.gwaa.R"
)

library(roxygen2)
setwd("R")
unlink("GenABEL",recursive=TRUE)
package.skeleton("GenABEL",code_files=roxy_files)
roxygenize("GenABEL",roxygen.dir="GenABEL",copy=F,unlink=F)
unlink("GenABEL/man/GenABEL-package.Rd",recursive=TRUE)
lstf <- paste("GenABEL/man/",list.files("GenABEL/man/"),sep="")
lstf
file.copy(lstf,"../man/",overwrite=TRUE)
unlink("GenABEL",recursive=TRUE)
